config/routes.rb
Rails.application.routes.draw do



  ActiveAdmin.routes(self)

     resources :users do
      resources :messages, only: [ :new, :create]

  end



  resources :agencies do
    collection do
      get "compare", to: "agencies#compare"
      post "compare", to: "agencies#compare"
      get 'search', to: "agencies#search"
      post 'search', to: "agencies#search"


    end






    resources :reviews, only: [:new, :create]
    resources :references, only: [:new, :create]
    resources :quotes, only: [:new, :create]
    resources :wishlists, only: [:index, :new, :create]


  end

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

#  require "sidekiq/web"
#  authenticate :user, lambda { |u| u.admin } do
#    mount Sidekiq::Web => '/sidekiq'
#  end

  devise_for :users



  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/agency.rb
class Agency < ApplicationRecord

  mount_uploader :photo, PhotoUploader


  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :references, dependent: :destroy

  has_many :quotes, dependent: :destroy
  has_many :wishlists, dependent: :destroy
  has_many :linkedin_reports
  has_many :github_reports

    include PgSearch


  after_save :enrich_github
  after_save :enrich_linkedin

  def review_mean
   if self.reviews.length == 0
      0
    else
      sum = self.reviews.reduce(0){|memo, review| memo+=review.star}
      sum.fdiv(self.reviews.count)
   end
  end




  def short_description
    "#{self.description[0..140]} ..." unless self.description.nil?
  end
  pg_search_scope :search_engine, against: [ :name, :description ]


  private


  def enrich_github
    unless self.github_account.nil?
      GithubEnrichmentJob.perform_later(self.id)
    end
  end


  def enrich_linkedin
    unless self.linkedin_account.nil?
      LinkedinEnrichmentJob.perform_later(self.id)
    end
  end

end

app/controllers/agencies_controller.rb
class AgenciesController < ApplicationController

<<<<<<< HEAD
  skip_before_action :authenticate_user!, only: [:compare, :index, :show, :add_wishlist]

  before_action :set_agency, only: [:show, :edit, :update, :destroy, :add_wishlist]



  # GET /agencies
  def index

    search_params = session['search_params']
    @agencies_selected = []

    unless search_params.nil?
      @agencies_selected = search_params['agencies'].reject{|k,v| v == "0"}.keys if search_params['agencies']
    end
    @agencies = Agency.all
  end

  def search

    condition = case params[:what]
    when "web" then { does_web_development: true }
    when "mobile" then { does_mobile_development: true }
    else {}
    end
    @agencies = Agency.where(condition)
  end



  # GET /agencies/1
  def show
    @agency = Agency.find(params[:id])
    @github_report = @agency.github_reports.last
    @linkedin_report = @agency.linkedin_reports.last
  end



  # GET /agencies/new
  def new
    @agency = Agency.new
  end

  # GET /agencies/1/edit
  def edit
  end

  # POST /agencies
  def create
    @agency = Agency.new(agency_params)


    if @agency.save
      AgencyMailer.create(@agency).deliver_now
      redirect_to @agency, notice: 'Agency was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /agencies/1
  def update
        @agency = Agency.find(params[:id])

    if @agency.update(agency_params)
      redirect_to @agency, notice: 'Agency was successfully updated.'
    else
      render :edit
    end
  end

  def compare

    session['search_params'] = params

    @agencies = params[:agencies] || []

    if
      @agencies.length == 0
      all_agencies = Agency.all
      @agencies_name = ["-"]
    else
         agencies = @agencies.reject{|k,v| v == '0'}.keys
      @agencies_name = agencies.map { |k,v| Agency.find(k).name }
      all_agencies = Agency.includes(:agency).where(agency: agencies)
    end

  end





      #     end
       #  end








  # DELETE /agencies/1
  def destroy
    @agency.destroy
    redirect_to agencies_url, notice: 'Agency was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_agency
      @agency = Agency.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def agency_params
      params.require(:agency).permit(:name, :description, :address, :user_id, :where, :photo, :photo_cache, :linkedin_account, :github_account)
    end

end

app/helpers/agencies_helper.rb
module AgenciesHelper



end

app/views/agencies/_agency.html.erb
<div class="agency-card">
  <%= cl_image_tag(agency.photo, height: 100, crop: :pad)  unless agency.photo.nil? %>

  <hr class="separator-card">
  <h2><%= agency.name %></h2>

  <p>
    <%= agency.short_description %>
  </p>
  <div class="stars">
    <% agency.review_mean.to_i.times do %>
      <i class="fa fa-star"></i>
    <% end %>
  </div>
</div>

app/views/agencies/_cards.html.erb
<div class="container">
  <h2 class="text-center uppercase">Nos derniers avis </h2>
  <div class="row">
    <% @agency.reviews.each do |review|%>
    <div class="col-xs-12 col-md-4">
      <div class="card-review">
        <%= image_tag review.user.photo, class:"avatar card-avatar"  %>
        <div class="card-star stars">
          <% review.star.to_i.times do %>
            <i class="fa fa-star"></i>
          <% end %>
        </div>
        <div class="card-title">
          <h4><%= review.user.full_name %></h4>
        </div>

        <div class="card-quote">
        <div class="quote-wrapper">
          <p class="quote-start quote-tick">"</p>
           <p class="quote-content"> <%= review.description %></p>
           <p class="quote-end quote-tick">"</p>
        </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/agencies/_form.html.erb
<%= simple_form_for(@agency) do |f| %>
  <%= f.error_notification %>


  <div class="form-inputs">

    <%= f.input :photo, label: "Votre Logo" %>


    <%= f.input :user_id, as: :hidden, :input_html => { :value => current_user.id.to_s } %>
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :address, label: "Adresse" %>


    <div class="padded-sm">
       <p class="form-advise">Augmenter votre visibilité grâce à votre compte LinkedIn</p>
      <%= f.input :linkedin_account, label: "Adresse de votre page LinkedIn", placeholder: "https://www.linkedin.com/company/google" %>
    </div>


    <div class="padded-sm">
      <p class="form-advise">Augmenter votre visibilité grâce à votre compte Github</p>
      <%= f.input :github_account, label: "Adresse de votre compte Github ", placeholder: "https://github.com/facebook"%>
    </div>

    <%= f.input :photo_cache, as: :hidden %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, value: "Enregistrer", class:"btn-primary pull-right" %>
    <%= link_to 'Annuler', agencies_path, class:"btn btn-danger"%>
  </div>
<% end %>

app/views/agencies/_references.html.erb
<div class="agency-card">
  <%= cl_image_tag(references.photo, height: 100, crop: :pad)  unless references.photo.nil? %>
  <hr class="separator-card">
  <h2><%= references.name %></h2>
  <p>
    <%= references.description %>
  </p>
</div>

app/views/agencies/compare.html.erb
<h1>comparaison</h1>

<div class="container">

<div class="row">
      <div class="col-xs-12 col-md-4">

<h4>Vos agences</h4>
        <% @agencies_name.each do |l| %>
          <h5><strong><%= l %></strong></h5>
        <% end %>

        <p>
          <%= link_to agencies_path, style: "font-size: 12px" do %>
            Changer de look
          <% end %>

        </p>

        <% @agencies.each do |key,value| %>
            <%= hidden_field_tag "agencies[#{key}]", value %>
        <% end %>

        <hr>



</div>

</div>
</div>

app/views/agencies/edit.html.erb
<h1>Editing Agency</h1>

<%= render 'form', agency: @agency %>

<%= link_to 'Show', @agency %> |
<%= link_to 'Back', agencies_path %>

app/views/agencies/index.html.erb
<ol class="breadcrumb">
         <li> <%= link_to "Accueil", root_path %> </li>
         <li class="active"><%= link_to "Toutes les agences", agencies_path  %> </li>
</ol>

<div class="agency-list">
  <div class="padded">
  <div class="container">
    <div class="row">
    <h1 class="text-center">Les agences suscesptibles de vous intéresser:</h1>
    <div class="separator">
    <div class="separator-line">
    </div>
    </div>
      <% @agencies.each do |agency| %>
        <div class="col-xs-12 col-md-4">
        <%= link_to agency_path(agency), class: 'link-agency-card' do %>

          <%= render "agencies/agency", :agency => agency %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  </div>

  <br>

  <%= form_tag compare_agencies_path, method: :get do %>

<div class="container">
        <div class="row">
          <% @agencies.each do |agency| %>
              <div class="col-xs-12 col-sm-4 col-md-3">
                <div class="card-look" >
                  <div class="card-name"><%= agency.name %> </div>

                  <div class="card-hover hide">
                    <!--     <p>Je suis une super look qui déchire </p> -->
                    <p><span><%= agency.description %></span></p>
                  </div>
                  <div class="card-check <%= 'hide' unless @agencies_selected.include?(agency.id.to_s) %>">
                    <i class="fa fa-check"></i>
                  </div>
                  <input type="hidden" name="agencies[<%= agency.id.to_s %>]" value="<%= @agencies_selected.include?(agency.id.to_s) ? '1' : '0' %>">
                </div>
              </div>
          <%end %>
        </div>
      </div>

          <div class="text-center">
        <input type="submit" value="Je découvre" class="btn navbar-wagon-button looks-cta">
      </div>

  <% end %>

  </div>







    <% content_for :after_js do %>
    <script>
      $(function(){
        $('.card-look').click(function() {
          $(this).children(".card-check").toggleClass('hide');
          var el = $(this).children('input[type=hidden]');
          el.val(el.val() == 0 ? 1 : 0);
        });
        $(".card-look").on("mouseover", function() {
          $(this).children(".card-hover").removeClass('hide');
        })
        $(".card-look").on("mouseout", function() {
          $(this).children(".card-hover").addClass('hide');
        })
      });
    </script>
<% end %>



  <%= link_to 'New Agency', new_agency_path %>
  <%= link_to 'Compare', compare_agencies_path, class: "btn btn-danger" %>


</div>

app/views/agencies/new.html.erb
<div class="padded">
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
        <h1>Ajouter votre agence</h1>

        <%= render 'form', agency: @agency %>


    </div>
  </div>
</div>

</div>

app/views/agencies/search.html.erb
<p id="notice"><%= notice %></p>

<% if @agencies.blank? %>
  <p class="padded text-center">
    Désolé, aucune agence ne correspond à votre recherche.
  </p>
<% else %>
<div class="padded">
  <div class="container">
    <div class="row">
    <h1 class="text-center">Vos agences :</h1>
            <% @agencies.each do |agency| %>
            <div class="col-xs-12 col-md-4">
              <%= link_to agency_path(agency), class: 'link-agency-card' do %>
              <%= render "agencies/agency", :agency => agency %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>







<br>
      <%= link_to 'Compare', compare_agencies_path, class: "btn btn-danger" %>


<%= link_to 'New Agency', new_agency_path %>
<% end %>
<%# link_to 'New Agency', new_agency_path %>

app/views/agencies/show.html.erb
<ol class="breadcrumb">
         <li> <%= link_to "Accueil", root_path %> </li>
         <li class=""><%= link_to "Toutes les agences", agencies_path  %> </li>
         <li class="active"><%= @agency.name%></li>
</ol>


<h1 class="text-center justify"></h1>

<div background-color:"#E8E8E8">
  <div class="container">

    <div class="row">
      <div class="col-xs-12 col-md-8" id="description">
        <%= cl_image_tag @agency.photo, crop: "pad", class: "logo-md pull-right" %>
        <p id="name-agency">
          <%= @agency.name %>
        </p>
        <p>
          <%= @agency.description %>
        </p>

        <% unless @linkedin_report.nil? %>
          <% @linkedin_report.specialities_array.each do |speciality|%>
          <div class="tag"> <%= speciality %> </div>
        <% end %>
        <% end %>
        <p>
          <% @agency.review_mean.to_i.times do %>
            <i class="fa fa-star"></i>
          <% end %>
        </p>
      </div>
      <div class="padded-agency">
      </div>
      <div class="col-xs-12 col-md-4" id="description2">

        <div class="col-xs-12 col-md-12" id="description3">
          <%= cl_image_tag "https://maps.googleapis.com/maps/api/staticmap?center=#{@agency.address}&size=600x300&maptype=roadmap", class: "full" %>
          <br>
          <br>
          <center>
          <%= link_to 'Demander un devis', new_agency_quote_path(@agency), :class => "btn btn-danger " %>
           <li>
            <%= link_to new_agency_wishlist_path(@agency), :class => "btn btn-danger" do %>

            <i class="fa fa-heart"></i>
          <% end %>
          </li>
          </center>
        </div>
      </div>
    </div>
    <div class="text-center" id="bottom-link">
      <% if current_user %>
        <%= link_to 'Ajouter un avis', new_agency_review_path(@agency) %> ou
        <%= link_to 'ajouter une référence', new_agency_reference_path(@agency) %>
        <% end %>
    </div>


    <% if @agency.references.any? %>
      <div class="padded">
        <h3 class="text-center uppercase with-margin"> References</h3>
        <div class="row">
         <% @agency.references.each do |r| %>
           <div class="col-xs-12 col-md-4">
            <%= render 'agencies/references', :references => r %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>

    <% if @agency.reviews.any?  %>
      <div class="padded">
        <h3 class="text-center uppercase with-margin"> Avis </h3>
        <div class="row">
          <% @agency.reviews.each do |review| %>
            <div class="col-xs-4">
              <%= render 'reviews/review_card', review: review %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>



  </div>
  </div>

app/views/agencies/show_more.html.erb
<p id="notice"><%= notice %></p>





<div class="padded">
<h1 class="text-center">Vos agences :</h1>
<div class="agency-card">
  <% @agencies.each do |agency| %>
  <%= cl_image_tag agency.photo, width: 300, height:  100, crop: :pad %>
  <h2><%= agency.name %></h2>
  <p> <%= agency.description %></p>
  <div class="stars">
    <% agency.review_mean.to_i.times do %>
      <i class="fa fa-star"></i>
    <% end %>
    <% end %>
  </div>
</div>

</div>

app/views/agencies/wishlist.html.erb
<div class="agency-list">
  <div class="padded">
  <div class="container">
    <div class="row">
    <h1 class="text-center">Les agences suscesptibles de vous intéresser:</h1>
    <div class="separator">
    <div class="separator-line">
    </div>
    </div>
      <% @agencies.each do |agency| %>
        <div class="col-xs-12 col-md-4">
        <%= link_to agency_path(agency) do %>

          <%= render "agencies/agency", :agency => agency %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  </div>
  </div>