config/routes.rb
Rails.application.routes.draw do



  ActiveAdmin.routes(self)

     resources :users do
      resources :messages, only: [ :new, :create]

  end



  resources :agencies do
    collection do
      get "compare", to: "agencies#compare"
      post "compare", to: "agencies#compare"
      get 'search', to: "agencies#search"
      post 'search', to: "agencies#search"


    end






    resources :reviews, only: [:new, :create]
    resources :references, only: [:new, :create]
    resources :quotes, only: [:new, :create]
    resources :wishlists, only: [:index, :new, :create]


  end

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

#  require "sidekiq/web"
#  authenticate :user, lambda { |u| u.admin } do
#    mount Sidekiq::Web => '/sidekiq'
#  end

  devise_for :users



  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/agency.rb
class Agency < ApplicationRecord

  mount_uploader :photo, PhotoUploader


  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :references, dependent: :destroy

  has_many :quotes, dependent: :destroy
  has_many :wishlists, dependent: :destroy
  has_many :linkedin_reports
  has_many :github_reports

    include PgSearch


  after_save :enrich_github
  after_save :enrich_linkedin

  def review_mean
   if self.reviews.length == 0
      0
    else
      sum = self.reviews.reduce(0){|memo, review| memo+=review.star}
      sum.fdiv(self.reviews.count)
   end
  end




  def short_description
    "#{self.description[0..140]} ..." unless self.description.nil?
  end
  pg_search_scope :search_engine, against: [ :name, :description ]


  private


  def enrich_github
    unless self.github_account.nil?
      GithubEnrichmentJob.perform_later(self.id)
    end
  end


  def enrich_linkedin
    unless self.linkedin_account.nil?
      LinkedinEnrichmentJob.perform_later(self.id)
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/github_report.rb
class GithubReport < ApplicationRecord
  belongs_to :agency


end

app/models/linkedin_report.rb
class LinkedinReport < ApplicationRecord
  belongs_to :agency


  def specialities_array
    self.specialities.split(",")
  end


end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :agency
    mount_uploader :pdf, PhotoUploader

end

app/models/reference.rb
class Reference < ApplicationRecord
  belongs_to :agency
  mount_uploader :photo, PhotoUploader

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :agency
  belongs_to :user
end

app/models/test.rb
class Test < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord

    mount_uploader :photo, PhotoUploader

  has_many :agencies, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :quotes, dependent: :destroy
  belongs_to :wishlist, dependent: :destroy
  has_many :messages, dependent: :destroy



  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  def full_name
    "#{first_name.try(:capitalize)} #{last_name.try(:capitalize)} "
  end

end

app/models/wishlist.rb
class Wishlist < ApplicationRecord

belongs_to :user
belongs_to :agency

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:home]
  def home
    @agencies = Agency.where(id: Review.group(:agency_id).count.keys).limit(3)
    @reviews = Review.where.not(user_id: nil).limit(3)
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :set_test, only: [:show, :edit, :update, :destroy]

  # GET /tests
  # GET /tests.json
  def index
    @tests = Test.all
  end

  # GET /tests/1
  # GET /tests/1.json
  def show
  end

  # GET /tests/new
  def new
    @test = Test.new
  end

  # GET /tests/1/edit
  def edit
  end

  # POST /tests
  # POST /tests.json
  def create
    @test = Test.new(test_params)

    respond_to do |format|
      if @test.save
        format.html { redirect_to @test, notice: 'Test was successfully created.' }
        format.json { render :show, status: :created, location: @test }
      else
        format.html { render :new }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tests/1
  # PATCH/PUT /tests/1.json
  def update
    respond_to do |format|
      if @test.update(test_params)
        format.html { redirect_to @test, notice: 'Test was successfully updated.' }
        format.json { render :show, status: :ok, location: @test }
      else
        format.html { render :edit }
        format.json { render json: @test.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tests/1
  # DELETE /tests/1.json
  def destroy
    @test.destroy
    respond_to do |format|
      format.html { redirect_to tests_url, notice: 'Test was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test
      @test = Test.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def test_params
      params.require(:test).permit(:t)
    end
end

app/helpers/agencies_helper.rb
module AgenciesHelper



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META['meta_title']
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META['meta_description']
  end

  def meta_image
    content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META['meta_image']
  end
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/layouts/_application.html.erb
<!DOCTYPE html>
<html>
  <head>
     <title>Devsolut</title>
      <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body class="<%= "#{controller_name} #{action_name}" %>">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

      <%= csrf_meta_tags %>
      <%= action_cable_meta_tag %>

      <title><%= meta_title %></title>
      <meta name="description" content="<%= meta_description %>">

      <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= image_url(meta_image) %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META[:twitter_account] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META[:twitter_account] %>">
    <meta name="twitter:image:src" content="<%= image_url(meta_image) %>">

    <!-- Google+ Schema.org markup -->
    <meta itemprop="name" content="<%= meta_title %>">
    <meta itemprop="description" content="<%= meta_description %>">
    <meta itemprop="image" content="<%= image_url(meta_image) %>">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= favicon_link_tag 'favicon.ico' %>
  </head>

  <body class="<%= "#{controller_name}-#{action_name}" %>">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
    <%= render 'shared/footer' %>

    <%= javascript_include_tag 'application' %>
    <%= yield :after_js %>
  </body>
</html>

app/views/pages/home.html.erb
    <div class="banner" style="background-image: linear-gradient(-225deg, rgba(255, 255, 255, 0.4) 100%, rgba(255, 255, 255, 0.4) 100%), url('<%= image_path "fondbanner3.png" %>')">
      <div class="banner-content">
          <h1>Trouvez les meilleures agences webs</h1>

<!-- Formulaire à refactoriser avec un form_tag -->
        <%= form_tag search_agencies_path, method: :get, class: 'form-inline'  do %>
        <%= select_tag "where", options_for_select([ "France", "Ile de France" ], "France"),  class: "form-control dropdown-toggle" %>
        <%= select_tag "what", options_for_select([ [ "Développement web", "web" ], [ "Développement mobile", "mobile" ] ], "Developpement web"), class: "form-control dropdown-toggle" %>
        <%= button_tag "Trouver", class: "btn btn-primary" %>
        <% end %>
<!-- end -->

      </div>
    </div>


<!-- A propos/services -->

<div class="padded">
  <div class="container">
    <h3 class="text-center">Nos services</h3>
    <div class="separator">
      <div class="separator-line">
      </div>
    </div>

    <div class="row">
      <div class="col-xs-12 col-sm-4">
      <div class="feature">
        <%= image_tag "bookmark.png"%>
        <h3>Catalogue</h3>
        <p>Accédez à un catalogue complet de toutes les agences de developpement web et mobile partout en France.</p>
      </div>
      </div>

      <div class="col-xs-12 col-sm-4">
      <div class="feature">

        <%= image_tag "diploma.png"%>
        <h3>Classement</h3>
        <p>Pour faire le bon choix visualisez les notes des agences sur 3 critères : compétences, influence, et avis clients. </p>
      </div>
      </div>


        <div class="col-xs-12 col-sm-4">
          <div class="feature">

          <%= image_tag "1456955809_clock.png"%>
          <h3>Devis et confidentialité</h3>
          <p>Obtenez en 48h un devis gratuit et un contrat de confidentialité pour des échanges en toute sécurité.</p>
          </div>
        </div>
    </div>
  </div>
</div>


<!-- Top des agences -->

<div class="padded padded-agency">
  <div class="container">
    <h2 class="text-center uppercase with-margin">Nos agences</h2>
    <div class="row">

      <% @agencies[0...3].each do |agency|%>
        <div class="col-xs-12 col-md-4">
          <%= link_to agency_path(agency), class: 'link-agency-card' do %>
            <%= render "agencies/agency", :agency => agency %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>


<!-- Testimonials -->

<div class="padded">
<div class="container">
  <h2 class="text-center uppercase with-margin">
    Nos derniers avis
  </h2>

  <div class="row">
    <% @reviews.each do |review|%>
      <div class="col-xs-12 col-md-4">
        <%= render 'reviews/review_card', review: review %>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">

  <div class="container">
    <div class="row">

      <div class="col-xs-6 pull-left">
        <ul class="list-inline">
          <li><a href=""><i class="fa fa-linkedin"></i></a></li>
          <li><a href=""><i class="fa fa-facebook"></i></a></li>
          <li><a href=""><i class="fa fa-twitter"></i></a></li>

        </ul>
      </div>

      <div class="col-xs-6 text-right">
        <p>@DEVSOLUT</p>
      </div>


    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>

  <%= image_tag "logo2.png", id: "logo2" %>
  <%= image_tag "logo-dev.png", id: "navbar-logo" %>


    <%= image_tag "logo-devsolut.png", id: "logo-devsolut" %>
    <%= image_tag "logo-dev.png", id: "navbar-logo" %>
  <% end %>



  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Se référencer"), new_agency_path, class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>