config/routes.rb
Rails.application.routes.draw do



  ActiveAdmin.routes(self)

     resources :users do
      resources :messages, only: [ :new, :create]

  end



  resources :agencies do
    collection do
      get "compare", to: "agencies#compare"
      post "compare", to: "agencies#compare"
      get 'search', to: "agencies#search"
      post 'search', to: "agencies#search"


    end






    resources :reviews, only: [:new, :create]
    resources :references, only: [:new, :create]
    resources :quotes, only: [:new, :create]
    resources :wishlists, only: [:index, :new, :create]


  end

  require "sidekiq/web"
  authenticate :user, lambda { |u| u.admin } do
    mount Sidekiq::Web => '/sidekiq'
  end

#  require "sidekiq/web"
#  authenticate :user, lambda { |u| u.admin } do
#    mount Sidekiq::Web => '/sidekiq'
#  end

  devise_for :users



  root to: 'pages#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/wishlist.rb
class Wishlist < ApplicationRecord

belongs_to :user
belongs_to :agency

end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController

skip_before_action :authenticate_user!, only: [:create]
<<<<<<< HEAD
before_action :set_agency, only: [:index ,:new, :edit, :update, :add_wishlist]

def index



  @wishlists = Wishlist.all


end




 def new
     if current_user.nil?
      redirect_to agency_path, alert: "Connectez-vous pour ajouter à votre wishlist"
      else
      @wishlist = Wishlist.new
      @wishlist.user = current_user
      @wishlist.agency = @agency
      if @wishlist.save
        redirect_to agency_wishlists_path(@agency), notice: "L'agence est maintenant dans votre wishlist"
        else
        redirect_to agency_path, alert: "Une erreur est survenu"
      end
    end

before_action :set_user, only: [:index, :edit, :update]





  def show
    @wishlist = Wishlist.find(params[:id])
  end

  # POST /reviews
  def create
    @wishlist = @agency.wishlist.new(wishlist_params)
    if @wishlist.save!
      redirect_to @wishlist, notice: 'Wishlist was successfully recorded.'
    else
      render @agency
    end
  end

  def edit
  end


  def update
      @wishlist = @user.wishlist.find(params[:id])
    if @wishlist.save!
      redirect_to @wishlist.user, notice: 'Wishlist was successfully recorded.'
    else
      render @agency
    end
  end

   def add_wishlist
    if current_user.nil?
      redirect_to agency_path, alert: "Connectez-vous pour ajouter à votre wishlist"
      else
      @wishlist = Wishlist.new
      @wishlist.user = current_user
      @wishlist.agency = @agency
      if @wishlist.save
        redirect_to agency_wishlists_path(@agency), notice: "L'agence est maintenant dans votre wishlist"
        else
        redirect_to agency_path, alert: "Une erreur est survenu"
      end
    end
  end




  private

    def set_agency
    @agency = Agency.find(params[:agency_id])
  end

    def wishlist_params
      params.require(:wishlist).permit(:agency_id)
    end

end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/_form.html.erb
<%= simple_form_for [@agency, @wishlist] do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
      <%= f.input :user_id, as: :hidden, :input_html => { :value => current_user.id.to_s } %>
          <%= f.button :submit %>
          <%= f.button :submit %>


  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/wishlists/add_wishlist.html.erb
<p id="notice"><%= notice %></p>

<h1>Wishlists</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <%= @wishlist.agency.photo %>
      <%= @wishlist.agency.name %>
        <%= @wishlist.agency.description %>



  </tbody>
   <tr>
      </tr>
</table>

<br>

app/views/wishlists/edit.html.erb
<h1>Editing Wishlist</h1>

<%= render 'form', wishlist: @wishlist %>

<%= link_to 'Show', @wishlist %> |
<%= link_to 'Back', wishlists_path %>

app/views/wishlists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wishlists !!!!!</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @wishlists.each do |wishlist| %>


    <%= wishlist.agency.photo %>
    <%= wishlist.agency.name %>
    <%= wishlist.agency.description %>

      <% end %>


  </tbody>
   <tr>
      </tr>
</table>

<br>

app/views/wishlists/new.html.erb
<h1>New Wishlist</h1>


<p id="notice"><%= notice %></p>

<h1>Wishlists !!!</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <%= @wishlist.agency.photo %>
    <%= @wishlist.agency.name %>
    <%= @wishlist.agency.description %>



  </tbody>
   <tr>
      </tr>
</table>

<br>




<%= link_to 'Back', wishlists_path %>

app/views/wishlists/show.html.erb
<p id="notice"><%= notice %></p>


<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wish.agency.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @wish.agency.description %>
</p>

<p>
  <strong> Logo:</strong>
  <%= @wish.agency.photo %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

<%= link_to 'Edit', edit_wishlist_path(@wishlist) %> |
<%= link_to 'Back', wishlists_path %>